name: Build and Deploy
on: 
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set gh-pages as worktree
        run: |
          git fetch --all
          git worktree add --track -b gh-pages2 scripts/temp-pages origin/gh-pages

      - name: Build
        run: |
          cd scripts
          tr -d '\15\32' < gh-pages-build.sh > gh-pages-build-2.sh
          chmod +x ./gh-pages-build-2.sh
          ./gh-pages-build-2.sh
          
      - name: Deploy to GitHub Pages
        run: |
          cd scripts/temp-pages
          cp -r ../temp-build/. .
          git config --global user.email "build-and-deploy-action@example.com"
          git config --global user.name "build-and-deploy-action"
          git add .
          git commit --allow-empty -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force